name: build
on:
  push:
    branches:
    - master
env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{github.repository}}
jobs:
  BuildATS4:
    runs-on: ubuntu-latest
    env:
      NAME: github-actions[bot]
      MAIL: github-actions[bot]@users.noreply.github.com
      HEAD: ${{github.event.head_commit.message}}
      DOCS: ./target/scala-2.13
      OPTS: --allow-empty
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v2
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - uses: docker/metadata-action@v4
      with:
        images: ${{env.REGISTRY}}/${{env.IMG_NAME}}
      id: meta
    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{steps.meta.outputs.tags}}
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: ${{env.DOCS}}
    - run: sbt doc
    - name: 'publish docs'
      run: |
        git config user.name  ${{env.NAME}}
        git config user.email ${{env.MAIL}}
        git add api
        git commit ${{env.OPTS}} -m '${{env.HEAD}}'
        git push
      working-directory: ${{env.DOCS}}
