name: build
on:
  push:
    branches:
    - master
env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{github.repository}}
jobs:
  BuildATS4:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - uses: docker/metadata-action@v4
      with:
        images: ${{env.REGISTRY}}/${{env.IMG_NAME}}
      id: meta
    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{steps.meta.outputs.tags}}
